image: timbru31/java-node

before_script:
  - nodejs -v
  - which nodejs
  - npm install -g grunt
  - npm install -g js-yaml

build:
  script:
    - mkdir -p tmp/mta
    - wget -nv --output-document=tmp/mta/mta.jar $MTA_BUILDER_URL
    - bash -ex build.sh
